evaluate-commands %sh{
    config_files="
        commands.kak
        common.kak
        recentf.kak
        plugins.kak
    "

    for file in $config_files; do
        printf "%s" "
            try %{
                source %{${kak_config:?}/$file}
            } catch %{
                echo -debug %val{error}
            }
        "
    done
}

kaktree-toggle

#kak-lsp
hook global WinSetOption filetype=(rust|python|go|javascript|typescript|c|cpp) %{
            lsp-enable-window
}
lsp-enable
lsp-auto-hover-enable
lsp-diagnostics-lines-enable

evaluate-commands %sh{
        find "${kak_runtime}"/../kakoune-extra-filetypes/rc -type f -name \*\\.kak -exec printf 'source %s\n' '{}' \;
}
