#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#### AUTOSTART ####
sxhkd &
picom &
/usr/bin/emacs --daemon & ### Start Emacs Server
$HOME/.config/polybar/launch.sh

### Setting wallpaper ###
feh --bg-scale ~/Pictures/Wallpapers/image16.png

### 一 二 三 四 五 六 七 八 九 十
bspc monitor -d "いち" に さん し ご ろく なな はち く じゅう

bspc config border_width        3
bspc config window_gap          12
bspc config top_padding         24

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#fbf1c7
#### BSPWM coloring ####
bspc config normal_border_color           "#282828"
bspc config active_border_color	      "#3c3836"
bspc config focused_border_color	      "#fbf1c7"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
